// Generate a browser-friendly ESM bundle of Pyret's tokenizer + GLR parser by
// concatenating the AMD modules (in dependency order) under a tiny define shim.
// Output: web/parser-bundle.js exporting { Tokenizer, PyretGrammar }.

import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import { existsSync } from "fs";

const HERE = dirname(fileURLToPath(import.meta.url));
// Prefer the local `pyret` symlink (-> ../pyret/lang) for dev; fall back to the
// vendored copy (vendor/pyret-lang) so the build is HERMETIC (works in CI / on a
// clean checkout with no external pyret checkout). The vendored files are the exact
// JS-GLR tokenizer + phase0 parser the seed needs.
const SYMLINK_LANG = resolve(HERE, "../pyret/lang");
const VENDOR_LANG = resolve(HERE, "../vendor/pyret-lang");
const LANG = existsSync(SYMLINK_LANG) ? SYMLINK_LANG : VENDOR_LANG;

const MODULES = [
  "lib/jglr/cyclicJSON.js",
  "lib/jglr/rnglr.js",
  "lib/jglr/jglr.js",
  "src/js/base/pyret-tokenizer.js",
  "build/phase0/js/pyret-parser.js",
];

const shim = `// AUTO-GENERATED by scripts/gen-parser-bundle.ts — do not edit.
// Pyret's tokenizer + GLR parser (AMD modules) bundled for the browser.
// The tokenizer's string processors use a sloppy-mode implicit global \`match\`;
// declare it here so the (strict-mode ESM) bundle doesn't ReferenceError.
var match;
const __amd = {};
function define(name, deps, factory) {
  if (typeof name !== "string") { factory = deps; deps = name; name = "__anon"; }
  if (typeof deps === "function") { factory = deps; deps = []; }
  const args = deps.map((d) => __amd[d]);
  __amd[name] = factory.apply(null, args) || __amd[name];
}
define.amd = true;
`;

let out = shim;
for (const m of MODULES) {
  const src = await Bun.file(resolve(LANG, m)).text();
  out += `\n// ===== ${m} =====\n` + src + "\n";
}
out += `
export const Tokenizer = __amd["pyret-base/js/pyret-tokenizer"];
export const PyretGrammar = __amd["pyret-base/js/pyret-parser"].PyretGrammar;
`;

const dest = resolve(HERE, "../web/parser-bundle.js");
await Bun.write(dest, out);
console.log(`wrote ${dest} (${out.length} bytes)`);
